### ISSUE TITLE
Hayward MaxFloVS integration?

### ISSUE THREAD

**Issue by TLCary** [kolcun/pool-control#1]
How did you connect the Arduino to the circuit board of the MaxFloVS?  
Oh, mine is a version 1, without the optional wall mounted plate.  I see a version 2 that has a RS485 connection as well as a 5 pin digital input.  (that would be handy)  I'm guessing yours is a Verison 2?
Thanks.
![maxflovs-circuitboard](https://user-images.githubusercontent.com/1626082/27055111-563f1f86-4f91-11e7-8a4e-052aa59401b4.jpg)

**Comment by kolcun** [comment]
Mine has a set of inputs, intended to be hooked up to external relays, as described on page 16 of this pdf - https://www.hayward-pool.com/pdf/manuals/MaxfloVs-IS2303VSP2.pdf

Perhaps it would be worth a call to Hayward tech support, to see if your model has these contacts available on the board.
